import type { ReplayInvocationModel, ReplayModel } from "./model.js";

export function exportReplayHtml(model: ReplayModel): string {
  const invocation = (item: ReplayInvocationModel): string => `<details open><summary>${escapeHtml(item.graphId ?? "Graph")} · ${escapeHtml(item.boundary ?? "unknown")}</summary><p><code>${escapeHtml(item.id)}</code></p>${events(item.events)}${item.children.map(invocation).join("")}</details>`;
  const events = (items: ReplayInvocationModel["events"]): string => `<ol>${items.map((item) => `<li><b>${escapeHtml(item.event.type)}</b><small>${escapeHtml(item.timestamp)}</small>${item.event.data === undefined ? "" : `<pre>${escapeHtml(JSON.stringify(item.event.data, null, 2))}</pre>`}</li>`).join("")}</ol>`;
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Loop Graph Replay ${escapeHtml(model.rootRunId)}</title><style>body{font:14px system-ui;max-width:1100px;margin:auto;padding:24px;color:#18212f}header{border-bottom:1px solid #ccd5e0}details{margin:12px 0;padding:10px;border:1px solid #ccd5e0;border-radius:8px}summary{font-weight:700;cursor:pointer}small{margin-left:12px;color:#667}pre{white-space:pre-wrap;max-height:22rem;overflow:auto;background:#f4f6f8;padding:10px;border-radius:6px}code{word-break:break-all}.bad{color:#a00}</style></head><body><header><h1>Loop Graph Replay</h1><p>Root Run <code>${escapeHtml(model.rootRunId)}</code></p><p>Recording: <b class="${model.recording.status === "complete" ? "" : "bad"}">${escapeHtml(model.recording.status)}</b></p></header><main><h2>Summary</h2><pre>${escapeHtml(JSON.stringify(model.summary, null, 2))}</pre><h2>Invocation tree</h2>${model.invocations.map(invocation).join("")}<h2>Root events</h2>${events(model.unscopedEvents)}<h2>Result</h2><details><summary>Show result</summary><pre>${escapeHtml(JSON.stringify(model.result, null, 2))}</pre></details></main></body></html>`;
}

export function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!); }
